# Uncomment the next line to define a global platform for your project
# platform :ios, '11.2'

target 'TablasyColeciones' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for TablasyColeciones
    
    pod "Alamofire"
    pod "SwiftyJSON"
    pod 'SCLAlertView', :git => 'https://github.com/vikmeup/SCLAlertView-Swift.git'
    pod 'Kingfisher'
    pod 'Proposer'
    pod 'Eureka'

     
   

    
    
    target 'TablasyColecionesTests' do
        inherit! :search_paths
        # Pods for testing
        
        
    end
    
    target 'TablasyColecionesUITests' do
        inherit! :search_paths
        # Pods for testing
        
    end
    
end
